#!/usr/bin/env bash

if [[ $EUID != 0 ]]; then
        sudo puppet apply --test --modulepath ./modules manifests/site.pp --hiera_config hiera.yaml
fi
puppet apply --test --modulepath ./modules manifests/site.pp --hiera_config hiera.yaml
