" Vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle.vim
call vundle#begin()
Plugin 'vundlevim/vundle.vim'

"" Plugins
Plugin 'airblade/vim-gitgutter.git'
Plugin 'bling/vim-airline.git'
Plugin 'kien/ctrlp.vim'
Plugin 'majutsushi/tagbar.git'
Plugin 'marijnh/tern_for_vim'
Plugin 'p8952/vim-colors-wombat.git'
Plugin 'rodjek/vim-puppet.git'
Plugin 'scrooloose/nerdtree.git'
Plugin 'scrooloose/syntastic.git'
Plugin 'terryma/vim-expand-region.git'
Plugin 'valloric/youcompleteme.git'
call vundle#end()

"" Core
set backspace=indent,eol,start
set cursorline
set encoding=utf-8
set lazyredraw
set mouse=
set nowrap
set number
set showcmd
set showmatch
set statusline=%t[%{strlen(&fenc)?&fenc:'none'}]%=Col:%c,Line:%l
set wildmenu

"" Tabs
set expandtab
set softtabstop=4
set tabstop=4

"" Style
colorscheme wombat256
set background=dark
set colorcolumn=80
set synmaxcol=180
syntax enable

"" Search
set hlsearch
set incsearch
set ignorecase

"" Filetype
filetype indent on
filetype on
filetype plugin on

"" Mappings
cnoreabbrev q  bp<bar>sp<bar>bn<bar>bd<CR>
cnoreabbrev wq w<bar>bp<bar>sp<bar>bn<bar>bd<CR>
let mapleader = "\<Space>"
map q: :q
nnoremap <Tab> :bnext<CR>

"" CtrlP
let g:ctrlp_match_window = 'bottom,order:ttb'
let g:ctrlp_max_depth=20
let g:ctrlp_max_files=0
let g:ctrlp_switch_buffer = 0
let g:ctrlp_working_path_mode = 0
map <C-p> :CtrlP

"" NERDTree
autocmd VimEnter * NERDTree
autocmd VimEnter * wincmd p
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
let g:NERDTreeDirArrows=0

"" Airline
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline#extensions#tabline#left_alt_sep = ''
let g:airline#extensions#tabline#left_sep = ''
let g:airline#extensions#tabline#right_alt_sep = ''
let g:airline#extensions#tabline#right_sep = ''
set timeoutlen=50

"" Expand Region
vmap <C-v> <Plug>(expand_region_shrink)
vmap v <Plug>(expand_region_expand)

"" YCM
let g:ycm_add_preview_to_completeopt=0
set completeopt-=preview
